process.env.FFMPEG_PATH = require('ffmpeg-static');
const sodium = require('libsodium-wrappers');

require('dotenv').config();
const fs   = require('fs');
const path = require('path');
const { spawn } = require('child_process');

const {
  Client, GatewayIntentBits, EmbedBuilder, ActivityType,
  ActionRowBuilder, ButtonBuilder, ButtonStyle,
  REST, Routes, SlashCommandBuilder,
} = require('discord.js');
const {
  joinVoiceChannel, createAudioPlayer, createAudioResource,
  AudioPlayerStatus, VoiceConnectionStatus, entersState, StreamType,
} = require('@discordjs/voice');
const ytdlp = require('yt-dlp-exec');

// ─── Cookie setup ─────────────────────────────────────────────────────────────
const rawCookiePath      = path.join(__dirname, 'cookies.txt');
const netscapeCookiePath = path.join(__dirname, 'cookies_netscape.txt');

function prepareNetscapeCookies() {
  try {
    if (!fs.existsSync(rawCookiePath)) return false;
    const raw = fs.readFileSync(rawCookiePath, 'utf-8').trim();
    if (raw.includes('# Netscape HTTP Cookie File')) {
      fs.copyFileSync(rawCookiePath, netscapeCookiePath); return true;
    }
    const lines = ['# Netscape HTTP Cookie File','# Generated by bot',''];
    raw.split(';').forEach(pair => {
      const [name,...rest] = pair.trim().split('=');
      if (!name||!rest.length) return;
      lines.push(`.youtube.com\tTRUE\t/\tTRUE\t1999999999\t${name.trim()}\t${rest.join('=').trim()}`);
    });
    fs.writeFileSync(netscapeCookiePath, lines.join('\n'));
    console.log('✅ Cookie dikonversi ke format Netscape');
    return true;
  } catch (err) { console.warn('⚠️ Cookie prep gagal:', err.message); return false; }
}
const hasCookies = prepareNetscapeCookies();
const cookiePath = hasCookies ? netscapeCookiePath : null;

// ─── yt-dlp binary ────────────────────────────────────────────────────────────
function getYtdlpBin() {
  try {
    const pkg = require('yt-dlp-exec');
    if (pkg.path && typeof pkg.path==='string') return pkg.path;
    if (typeof pkg==='string') return pkg;
    const b = path.join(__dirname,'..','node_modules','yt-dlp-exec','bin','yt-dlp');
    if (fs.existsSync(b+'.exe')) return b+'.exe';
    if (fs.existsSync(b))        return b;
  } catch(e){ console.error('getYtdlpBin:',e.message); }
  throw new Error('yt-dlp binary tidak ditemukan.');
}
const ytdlpBin = getYtdlpBin();
console.log('✅ yt-dlp binary:', ytdlpBin);

// ─── Slash commands ───────────────────────────────────────────────────────────
const slashCommands = [
  // Playback
  new SlashCommandBuilder().setName('play').setDescription('Putar lagu dari YouTube')
    .addStringOption(o=>o.setName('lagu').setDescription('Nama lagu atau link YouTube').setRequired(true)),
  new SlashCommandBuilder().setName('p').setDescription('Shortcut: Putar lagu dari YouTube')
    .addStringOption(o=>o.setName('lagu').setDescription('Nama lagu atau link YouTube').setRequired(true)),
  new SlashCommandBuilder().setName('skip').setDescription('Skip lagu yang sedang diputar'),
  new SlashCommandBuilder().setName('s').setDescription('Shortcut: Skip lagu yang sedang diputar'),
  new SlashCommandBuilder().setName('stop').setDescription('Stop musik dan bot keluar dari voice channel'),
  new SlashCommandBuilder().setName('pause').setDescription('Pause musik sementara'),
  new SlashCommandBuilder().setName('resume').setDescription('Lanjutkan musik yang di-pause'),
  new SlashCommandBuilder().setName('r').setDescription('Shortcut: Lanjutkan musik yang di-pause'),
  // Controls
  new SlashCommandBuilder().setName('controls').setDescription('Buka panel kontrol musik (embed + tombol)'),
  new SlashCommandBuilder().setName('control').setDescription('Buka panel kontrol musik (embed + tombol)'),
  new SlashCommandBuilder().setName('c').setDescription('Shortcut: Buka panel kontrol musik'),
  new SlashCommandBuilder().setName('ct').setDescription('Shortcut: Buka panel kontrol musik'),
  // Queue
  new SlashCommandBuilder().setName('queue').setDescription('Lihat daftar antrian lagu'),
  new SlashCommandBuilder().setName('q').setDescription('Shortcut: Lihat daftar antrian lagu'),
  new SlashCommandBuilder().setName('clear').setDescription('Hapus semua lagu di antrian'),
  new SlashCommandBuilder().setName('nowplaying').setDescription('Lihat lagu yang sedang diputar'),
  new SlashCommandBuilder().setName('np').setDescription('Shortcut: Lihat lagu yang sedang diputar'),
  // Mode
  new SlashCommandBuilder().setName('loop').setDescription('Toggle loop — ulang lagu yang sedang diputar'),
  new SlashCommandBuilder().setName('l').setDescription('Shortcut: Toggle loop'),
  new SlashCommandBuilder().setName('autoplay').setDescription('Toggle autoplay — putar lagu terkait otomatis saat antrian habis'),
  new SlashCommandBuilder().setName('ap').setDescription('Shortcut: Toggle autoplay'),
  // Search
  new SlashCommandBuilder().setName('search').setDescription('Cari lagu dan pilih dari hasil pencarian')
    .addStringOption(o=>o.setName('query').setDescription('Nama lagu yang dicari').setRequired(true)),
  new SlashCommandBuilder().setName('sc').setDescription('Shortcut: Cari lagu dan pilih dari hasil pencarian')
    .addStringOption(o=>o.setName('query').setDescription('Nama lagu yang dicari').setRequired(true)),
  // Info
  new SlashCommandBuilder().setName('help').setDescription('Lihat semua command bot'),
  new SlashCommandBuilder().setName('h').setDescription('Shortcut: Lihat semua command bot'),
  new SlashCommandBuilder().setName('aliases').setDescription('Lihat semua command dan shortcut-nya'),
  new SlashCommandBuilder().setName('changelog').setDescription('Lihat versi dan perubahan bot'),
].map(c=>c.toJSON());

// ─── State per server ─────────────────────────────────────────────────────────
const queues = new Map();
function getQueue(guildId) {
  if (!queues.has(guildId)) {
    queues.set(guildId, {
      connection:null, player:null,
      tracks:[], history:[], loop:false, autoplay:false,
      currentTrack:null, playerMsg:null, startTime:null,
      textChannel:null,
      isTransitioning:false,
      ytdlpProc:null, // referensi proses yt-dlp yang sedang berjalan
    });
  }
  return queues.get(guildId);
}

// ─── Helpers ──────────────────────────────────────────────────────────────────
function formatDuration(sec) {
  sec = Math.floor(sec||0);
  const h=Math.floor(sec/3600), m=Math.floor((sec%3600)/60), s=sec%60;
  if (h>0) return `${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;
  return `${m}:${String(s).padStart(2,'0')}`;
}
function parseDuration(str) {
  if (!str||str==='N/A') return 0;
  const p=str.split(':').map(Number);
  if (p.length===3) return p[0]*3600+p[1]*60+p[2];
  if (p.length===2) return p[0]*60+p[1];
  return 0;
}
function buildProgressBar(elapsed, total, width=18) {
  if (!total) return '▬'.repeat(width);
  const pos=Math.min(Math.floor((elapsed/total)*width), width-1);
  return '▬'.repeat(pos)+'🔘'+'▬'.repeat(width-pos);
}
function cleanQuery(q) {
  q=q.replace(/<(https?:\/\/[^>]+)>/g,'$1');
  q=q.replace(/\[.*?\]\((https?:\/\/[^)]+)\)/g,'$1');
  return q.trim();
}
async function safeEdit(msg, content, opts={}) {
  try {
    if (!msg?.editable) return;
    if (content?.length>2000) content=content.slice(0,1997)+'...';
    await msg.edit({ content, ...opts });
  } catch(err){ if(err.code!==10008) console.error('safeEdit:',err.message); }
}

// ─── Player embed builder ─────────────────────────────────────────────────────
function buildPlayerEmbed(track, queue, elapsed) {
  const totalSec=parseDuration(track.duration);
  const bar=buildProgressBar(elapsed, totalSec);
  const next=queue.tracks[0];
  return {
    embeds:[new EmbedBuilder()
      .setColor(0x5865f2)
      .setAuthor({name:'▶️  Now Playing'})
      .setTitle(track.title).setURL(track.url)
      .setThumbnail(track.thumbnail||null)
      .setDescription(`\`${bar}\`\n\`${formatDuration(elapsed)} / ${track.duration||'?:??'}\``)
      .addFields(
        {name:'📋 Antrian', value:queue.tracks.length
          ? `${queue.tracks.length} lagu — berikutnya: **${next.title.slice(0,40)}**`
          : 'Kosong', inline:false},
        {name:'🔁 Loop',     value:queue.loop    ?'`ON`':'`OFF`', inline:true},
        {name:'🔀 Autoplay', value:queue.autoplay?'`ON`':'`OFF`', inline:true},
        {name:'👤 Request',  value:track.requester,               inline:true},
      )
      .setFooter({text:'Gunakan tombol di bawah untuk kontrol musik'})
    ],
    components:[new ActionRowBuilder().addComponents(
      new ButtonBuilder().setCustomId('btn_prev').setEmoji('⏮').setStyle(ButtonStyle.Secondary),
      new ButtonBuilder().setCustomId('btn_pause').setEmoji('⏸').setStyle(ButtonStyle.Primary),
      new ButtonBuilder().setCustomId('btn_skip').setEmoji('⏭').setStyle(ButtonStyle.Secondary),
      new ButtonBuilder().setCustomId('btn_stop').setEmoji('✖').setStyle(ButtonStyle.Danger),
      new ButtonBuilder().setCustomId('btn_loop').setEmoji('🔁').setStyle(queue.loop?ButtonStyle.Success:ButtonStyle.Secondary),
    )],
  };
}
function buildPausedEmbed(track, queue) {
  return {
    embeds:[new EmbedBuilder()
      .setColor(0xfaa61a).setAuthor({name:'⏸  Paused'})
      .setTitle(track.title).setURL(track.url)
      .setThumbnail(track.thumbnail||null)
      .setDescription('Musik sedang di-pause.')
      .addFields(
        {name:'🔁 Loop',     value:queue.loop    ?'`ON`':'`OFF`', inline:true},
        {name:'🔀 Autoplay', value:queue.autoplay?'`ON`':'`OFF`', inline:true},
      )
    ],
    components:[new ActionRowBuilder().addComponents(
      new ButtonBuilder().setCustomId('btn_prev').setEmoji('⏮').setStyle(ButtonStyle.Secondary),
      new ButtonBuilder().setCustomId('btn_resume').setEmoji('▶️').setStyle(ButtonStyle.Success),
      new ButtonBuilder().setCustomId('btn_skip').setEmoji('⏭').setStyle(ButtonStyle.Secondary),
      new ButtonBuilder().setCustomId('btn_stop').setEmoji('✖').setStyle(ButtonStyle.Danger),
      new ButtonBuilder().setCustomId('btn_loop').setEmoji('🔁').setStyle(queue.loop?ButtonStyle.Success:ButtonStyle.Secondary),
    )],
  };
}

// ─── Search ───────────────────────────────────────────────────────────────────
async function searchTrack(query, requester) {
  const isUrl=/^https?:\/\//i.test(query);
  const searchQuery=isUrl?query:`ytsearch1:${query}`;
  const args={
    dumpSingleJson:true, noCheckCertificates:true,
    noWarnings:true, preferFreeFormats:true,
    skipDownload:true,
    // Spoof sebagai iOS app — lebih susah dideteksi YouTube dibanding bot
    extractorArgs:'youtube:player_client=ios',
    ...(isUrl?{flatPlaylist:true}:{}),
    ...(hasCookies?{cookies:cookiePath}:{}),
  };
  const info=await ytdlp(searchQuery,args).catch(err=>{
    console.error('yt-dlp error:',err.message);
    throw new Error('Gagal mengambil info lagu');
  });
  const v=info.entries?info.entries[0]:info;
  // webpage_url ada kalau full fetch; url ada kalau flat-playlist / search result
  const videoUrl=v?.webpage_url||v?.url||(v?.id?`https://www.youtube.com/watch?v=${v.id}`:null);
  if (!videoUrl) throw new Error('Lagu tidak ditemukan.');
  return {
    title:    v.title||'Unknown',
    url:      videoUrl,
    duration: v.duration?formatDuration(v.duration):'N/A',
    thumbnail:v.thumbnail||null,
    videoId:  v.id||null,
    requester,
  };
}

// Cari 5 hasil sekaligus untuk fitur /search
async function searchMultiple(query, requester, count=5) {
  const info=await ytdlp(`ytsearch${count}:${query}`,{
    dumpSingleJson:true, noCheckCertificates:true,
    noWarnings:true, skipDownload:true,
    extractorArgs:'youtube:player_client=ios',
    ...(hasCookies?{cookies:cookiePath}:{}),
  }).catch(err=>{ throw new Error('Gagal mencari lagu: '+err.message); });

  const entries=info?.entries||[];
  if (!entries.length) throw new Error('Tidak ada hasil ditemukan.');

  return entries.map(v=>({
    title:    v.title||'Unknown',
    url:      v.webpage_url||v.url||(v.id?`https://www.youtube.com/watch?v=${v.id}`:null),
    duration: v.duration?formatDuration(v.duration):'N/A',
    thumbnail:v.thumbnail||null,
    videoId:  v.id||null,
    requester,
  })).filter(v=>v.url);
}
  // Strategi 1: YouTube Auto-Mix / Radio (RD + videoId) — paling akurat
  try {
    const mixUrl=`https://www.youtube.com/watch?v=${videoId}&list=RD${videoId}`;
    const info=await ytdlp(mixUrl,{
      dumpSingleJson:true, noCheckCertificates:true,
      noWarnings:true, skipDownload:true, flatPlaylist:true,
      extractorArgs:'youtube:player_client=ios',
      playlistItems:'2-8',
      ...(hasCookies?{cookies:cookiePath}:{}),
    });
    const entries=info?.entries?.filter(v=>v.id && v.id!==videoId);
    if (entries?.length) {
      const pick=entries[Math.floor(Math.random()*Math.min(entries.length,4))];
      const videoUrl=pick.webpage_url||pick.url||`https://www.youtube.com/watch?v=${pick.id}`;
      console.log(`🔀 Autoplay (mix): ${pick.title}`);
      return {
        title:    pick.title||'Unknown',
        url:      videoUrl,
        duration: pick.duration?formatDuration(pick.duration):'N/A',
        thumbnail:pick.thumbnail||null,
        videoId:  pick.id||null,
        requester,
      };
    }
  } catch(err){ console.warn('getRelatedTrack (mix):', err.message); }

  // Strategi 2: Search by judul lagu sebagai fallback
  try {
    const info=await ytdlp(`ytsearch5:${title}`,{
      dumpSingleJson:true, noCheckCertificates:true,
      noWarnings:true, skipDownload:true,
      extractorArgs:'youtube:player_client=ios',
      ...(hasCookies?{cookies:cookiePath}:{}),
    });
    const entries=info?.entries?.filter(v=>v.id && v.id!==videoId);
    if (entries?.length) {
      const pick=entries[Math.floor(Math.random()*Math.min(entries.length,3))];
      const videoUrl=pick.webpage_url||pick.url||`https://www.youtube.com/watch?v=${pick.id}`;
      console.log(`🔀 Autoplay (search): ${pick.title}`);
      return {
        title:    pick.title||'Unknown',
        url:      videoUrl,
        duration: pick.duration?formatDuration(pick.duration):'N/A',
        thumbnail:pick.thumbnail||null,
        videoId:  pick.id||null,
        requester,
      };
    }
  } catch(err){ console.warn('getRelatedTrack (search):', err.message); }

  return null;
}

// ─── Stream ───────────────────────────────────────────────────────────────────
function createYtdlpStream(url) {
  const args=[
    url,'-o','-',
    '-f','bestaudio[ext=webm]/bestaudio/best',
    '--no-playlist','--quiet','--no-warnings',
    // Spoof sebagai iOS — bypass bot detection YouTube
    '--extractor-args','youtube:player_client=ios',
    ...(hasCookies?['--cookies',cookiePath]:[]),
  ];
  const proc=spawn(ytdlpBin, args, {stdio:['ignore','pipe','pipe']});
  proc.stderr.on('data', d=>{
    const m=d.toString().trim();
    if(m && !m.includes('Broken pipe') && !m.includes('unable to write data')) console.warn('[yt-dlp]',m);
  });
  proc.on('error', err=>console.error('[yt-dlp spawn]',err.message));
  proc.stdout.on('error', ()=>{}); // suppress EPIPE / premature close saat skip
  return { stream: proc.stdout, proc };
}

// ─── Client ───────────────────────────────────────────────────────────────────
const client=new Client({
  intents:[
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildVoiceStates,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.MessageContent,
  ],
});

client.once('clientReady', async c=>{
  console.log(`✅ Bot online sebagai ${c.user.tag}`);
  c.user.setActivity('🎵 /play <lagu>', {type:ActivityType.Listening});
  try {
    const rest=new REST({version:'10'}).setToken(process.env.DISCORD_TOKEN);
    await rest.put(Routes.applicationCommands(c.user.id), {body:slashCommands});
    console.log(`✅ ${slashCommands.length} slash commands terdaftar`);
  } catch(err){ console.error('❌ Gagal register slash commands:',err.message); }
});

// ─── playNext ─────────────────────────────────────────────────────────────────
async function playNext(guildId) {
  const queue=getQueue(guildId);
  const textChannel=queue.textChannel;

  // Nonaktifkan tombol di player lama tanpa menghapus pesan
  if (queue.playerMsg) {
    try {
      await queue.playerMsg.edit({
        embeds: queue.playerMsg.embeds,
        components:[]
      });
    } catch(_){}
    queue.playerMsg=null;
  }

  // Autoplay kalau antrian kosong
  if (!queue.tracks.length && queue.autoplay && queue.currentTrack?.videoId) {
    const related=await getRelatedTrack(queue.currentTrack.videoId, queue.currentTrack.title, 'Autoplay');
    if (related) {
      queue.tracks.push(related);
      if (textChannel) textChannel.send({
        embeds:[new EmbedBuilder().setColor(0x43b581)
          .setDescription(`🔀 **Autoplay:** [${related.title}](${related.url})`)]
      }).catch(()=>{});
    }
  }

  if (!queue.tracks.length) {
    queue.currentTrack=null;
    if (textChannel) textChannel.send('✅ Antrian habis!').catch(()=>{});
    return;
  }

  const track=queue.tracks.shift();
  // Simpan ke history sebelum ganti currentTrack (max 20 lagu)
  if (queue.currentTrack) {
    queue.history.push({...queue.currentTrack});
    if (queue.history.length > 20) queue.history.shift();
  }
  queue.currentTrack=track;
  queue.startTime=Date.now();

  // Kill proses yt-dlp sebelumnya kalau masih jalan
  if (queue.ytdlpProc) {
    try { queue.ytdlpProc.kill('SIGKILL'); } catch(_){}
    queue.ytdlpProc=null;
  }

  try {
    const {stream, proc}=createYtdlpStream(track.url);
    queue.ytdlpProc=proc; // simpan referensi untuk di-kill saat skip
    const resource=createAudioResource(stream,{inputType:StreamType.Arbitrary});
    queue.player.play(resource);
    if (textChannel) {
      queue.playerMsg=await textChannel.send(buildPlayerEmbed(track,queue,0)).catch(()=>null);
    }
  } catch(err){
    console.error('playNext error:',err.message);
    if (textChannel) textChannel.send(`❌ Gagal memutar **${track.title}**: ${err.message}`).catch(()=>{});
    setTimeout(()=>playNext(guildId), 1000);
  }
}

// ─── Setup player untuk guild ─────────────────────────────────────────────────
function setupPlayer(guildId) {
  const queue=getQueue(guildId);
  if (queue.player) return; // sudah ada

  queue.player=createAudioPlayer();
  queue.connection.subscribe(queue.player);

  queue.player.on(AudioPlayerStatus.Idle, ()=>{
    if (queue.isTransitioning) return; // sudah ada yang handle
    queue.isTransitioning=true;
    if (queue.loop && queue.currentTrack) {
      queue.tracks.unshift({...queue.currentTrack});
    }
    setTimeout(()=>{ queue.isTransitioning=false; playNext(guildId); }, 500);
  });

  queue.player.on('error', err=>{
    console.error('Player error:',err.message);
    if (queue.isTransitioning) return; // Idle sudah handle, abaikan error dari stream kill
    queue.isTransitioning=true;
    if (queue.textChannel) queue.textChannel.send(`❌ Error: ${err.message}`).catch(()=>{});
    setTimeout(()=>{ queue.isTransitioning=false; playNext(guildId); }, 1000);
  });
}

// ─── handlePlay ───────────────────────────────────────────────────────────────
async function handlePlay(ctx, query, guildId, voiceChannel, textChannel, username) {
  const queue=getQueue(guildId);
  queue.textChannel=textChannel;

  const replyFn=async(content,opts={})=>{
    try {
      if (ctx.isChatInputCommand?.()) {
        if (ctx.deferred||ctx.replied) return ctx.editReply({content,...opts});
        return ctx.reply({content,...opts});
      }
      return safeEdit(ctx, content, opts);
    } catch(_){}
  };

  let trackInfo;
  try { trackInfo=await searchTrack(query, username); }
  catch(err){
    console.error('searchTrack:',err.message);
    return replyFn('❌ Gagal cari lagu. Coba link YouTube langsung.');
  }

  queue.tracks.push(trackInfo);

  if (!queue.connection) {
    try {
      queue.connection=joinVoiceChannel({
        channelId:voiceChannel.id,
        guildId,
        adapterCreator:voiceChannel.guild.voiceAdapterCreator,
        selfDeaf:true,
      });
      await entersState(queue.connection, VoiceConnectionStatus.Ready, 15_000);
    } catch(err){
      if (queue.connection){queue.connection.destroy();queue.connection=null;}
      queue.tracks.pop();
      return replyFn(`❌ Gagal join VC: ${err.message}`);
    }

    setupPlayer(guildId);

    if (ctx.isChatInputCommand?.()) await replyFn(`✅ Memutar **${trackInfo.title}**`);
    else { try{await ctx.delete();}catch(_){} }

    playNext(guildId);

  } else {
    setupPlayer(guildId); // pastikan player ada
    const embed=new EmbedBuilder().setColor(0x1db954).setTitle('➕ Ditambahkan ke Antrian')
      .setDescription(`**[${trackInfo.title}](${trackInfo.url})**`)
      .addFields(
        {name:'⏱ Durasi',  value:trackInfo.duration,           inline:true},
        {name:'👤 Request', value:trackInfo.requester,           inline:true},
        {name:'📋 Posisi',  value:`#${queue.tracks.length}`,    inline:true}
      ).setThumbnail(trackInfo.thumbnail);
    await replyFn('',{embeds:[embed]});

    // Kalau tidak ada yang diputar (antrian habis sebelumnya), langsung putar
    if (!queue.currentTrack) playNext(guildId);
  }
}

// ─── Button handler ───────────────────────────────────────────────────────────
client.on('interactionCreate', async interaction=>{
  if (interaction.isButton()) {
    const queue=getQueue(interaction.guildId);
    await interaction.deferUpdate().catch(()=>{});

    switch(interaction.customId){
      case 'btn_pause':
        if (queue.player?.state.status===AudioPlayerStatus.Playing){
          queue.player.pause();
          if (queue.playerMsg&&queue.currentTrack)
            await safeEdit(queue.playerMsg,'',buildPausedEmbed(queue.currentTrack,queue));
        }
        break;
      case 'btn_resume':
        if (queue.player?.state.status===AudioPlayerStatus.Paused){
          queue.player.unpause();
          if (queue.playerMsg&&queue.currentTrack)
            await safeEdit(queue.playerMsg,'',buildPlayerEmbed(queue.currentTrack,queue,0));
        }
        break;
      case 'btn_skip':
        if (!queue.player || !queue.currentTrack) break;
        queue.loop=false;
        // Kill yt-dlp lama, langsung play berikutnya — tidak pakai stop() biar tidak ada double Idle event
        if (queue.ytdlpProc) { try{queue.ytdlpProc.kill('SIGKILL');}catch(_){} queue.ytdlpProc=null; }
        playNext(interaction.guildId);
        break;
      case 'btn_stop':
        queue.tracks=[];queue.currentTrack=null;queue.loop=false;
        if (queue.player){queue.player.removeAllListeners();queue.player.stop(true);}
        queue.connection?.destroy();
        if (queue.playerMsg) await safeEdit(queue.playerMsg,'⏹️ Musik dihentikan.',{embeds:[],components:[]});
        queue.playerMsg=null;queue.connection=null;queue.player=null;
        queues.delete(interaction.guildId);
        break;
      case 'btn_loop':
        queue.loop=!queue.loop;
        if (queue.playerMsg&&queue.currentTrack){
          const el=queue.startTime?(Date.now()-queue.startTime)/1000:0;
          await safeEdit(queue.playerMsg,'',buildPlayerEmbed(queue.currentTrack,queue,el));
        }
        break;
      case 'btn_prev':
        if (!queue.player) break;
        queue.loop=false;
        if (queue.history && queue.history.length > 0) {
          const prevTrack=queue.history.pop();
          if (queue.currentTrack) queue.tracks.unshift({...queue.currentTrack});
          queue.tracks.unshift(prevTrack);
        } else if (queue.currentTrack) {
          queue.tracks.unshift({...queue.currentTrack});
        } else { break; }
        if (queue.ytdlpProc) { try{queue.ytdlpProc.kill('SIGKILL');}catch(_){} queue.ytdlpProc=null; }
        queue.currentTrack=null;
        playNext(interaction.guildId);
        break;
      default:
        // Handler tombol hasil search: format customId = "search_pick_{index}_{url}"
        if (interaction.customId.startsWith('search_pick_')) {
          const url=interaction.customId.split('search_pick_')[1];
          const vc=interaction.member?.voice?.channel;
          if (!vc) {
            await interaction.update({content:'❌ Join voice channel dulu!', embeds:[], components:[]});
            return;
          }
          await interaction.update({content:`🔍 Memuat...`, embeds:[], components:[]});
          await handlePlay(interaction, url, interaction.guildId, vc, interaction.channel, interaction.user.username);
        }
        break;
    }
    return;
  }

  // ─── Slash commands ──────────────────────────────────────────────────────
  if (!interaction.isChatInputCommand()) return;
  const {commandName, guildId}=interaction;
  if (!guildId) return interaction.reply({content:'❌ Hanya bisa di server.',ephemeral:true});

  const queue=getQueue(guildId);

  // Play aliases
  if (commandName==='play'||commandName==='p') {
    const query=cleanQuery(interaction.options.getString('lagu'));
    await interaction.deferReply();
    const vc=interaction.member?.voice?.channel;
    if (!vc) return interaction.editReply('❌ Join voice channel dulu!');
    return handlePlay(interaction, query, guildId, vc, interaction.channel, interaction.user.username);
  }

  // Search aliases
  if (commandName==='search'||commandName==='sc') {
    const query=cleanQuery(interaction.options.getString('query'));
    await interaction.deferReply();
    let results;
    try { results=await searchMultiple(query, interaction.user.username); }
    catch(err){ return interaction.editReply(`❌ ${err.message}`); }

    // Buat embed daftar hasil
    const desc=results.map((t,i)=>`\`${i+1}.\` [${t.title}](${t.url}) \`${t.duration}\``).join('\n');
    const embed=new EmbedBuilder()
      .setColor(0x5865f2)
      .setTitle(`🔍 Hasil pencarian: "${query}"`)
      .setDescription(desc)
      .setFooter({text:'Klik tombol untuk memutar lagu'});

    // Buat tombol 1-5 per hasil
    const row=new ActionRowBuilder().addComponents(
      results.map((t,i)=>
        new ButtonBuilder()
          .setCustomId(`search_pick_${t.url}`)
          .setLabel(`${i+1}. ${t.title.slice(0,40)}`)
          .setStyle(ButtonStyle.Secondary)
      )
    );

    return interaction.editReply({embeds:[embed], components:[row]});
  }

  // Skip aliases
  if (commandName==='skip'||commandName==='s') {
    if (!queue.player||!queue.currentTrack) return interaction.reply({content:'❌ Tidak ada yang diputar.',ephemeral:true});
    await interaction.reply({content:'⏭️ Di-skip!',ephemeral:true});
    queue.loop=false;
    if (queue.ytdlpProc) { try{queue.ytdlpProc.kill('SIGKILL');}catch(_){} queue.ytdlpProc=null; }
    playNext(guildId);
    return;
  }

  // Controls aliases
  if (['controls','control','c','ct'].includes(commandName)) {
    if (!queue.currentTrack) return interaction.reply({content:'❌ Tidak ada yang diputar.',ephemeral:true});
    const el=queue.startTime?(Date.now()-queue.startTime)/1000:0;
    return interaction.reply(buildPlayerEmbed(queue.currentTrack,queue,el));
  }

  switch(commandName){
    case 'stop':
      if (!queue.connection) return interaction.reply({content:'❌ Bot tidak di VC.',ephemeral:true});
      queue.tracks=[];queue.currentTrack=null;queue.loop=false;
      if (queue.player){queue.player.removeAllListeners();queue.player.stop(true);}
      queue.connection?.destroy();
      if (queue.playerMsg) await safeEdit(queue.playerMsg,'⏹️ Musik dihentikan.',{embeds:[],components:[]});
      queue.playerMsg=null;queue.connection=null;queue.player=null;
      queues.delete(guildId);
      return interaction.reply({content:'⏹️ Bot keluar VC.',ephemeral:true});

    case 'pause':
      if (!queue.player) return interaction.reply({content:'❌ Tidak ada yang diputar.',ephemeral:true});
      queue.player.pause();
      if (queue.playerMsg&&queue.currentTrack) await safeEdit(queue.playerMsg,'',buildPausedEmbed(queue.currentTrack,queue));
      return interaction.reply({content:'⏸️ Di-pause.',ephemeral:true});

    case 'resume': case 'r':
      if (!queue.player) return interaction.reply({content:'❌ Tidak ada yang diputar.',ephemeral:true});
      queue.player.unpause();
      if (queue.playerMsg&&queue.currentTrack) await safeEdit(queue.playerMsg,'',buildPlayerEmbed(queue.currentTrack,queue,0));
      return interaction.reply({content:'▶️ Dilanjutkan.',ephemeral:true});

    case 'loop': case 'l':
      queue.loop=!queue.loop;
      if (queue.playerMsg&&queue.currentTrack){
        const el=queue.startTime?(Date.now()-queue.startTime)/1000:0;
        await safeEdit(queue.playerMsg,'',buildPlayerEmbed(queue.currentTrack,queue,el));
      }
      return interaction.reply({content:`🔁 Loop **${queue.loop?'ON':'OFF'}**.`,ephemeral:true});

    case 'autoplay': case 'ap':
      queue.autoplay=!queue.autoplay;
      if (queue.playerMsg&&queue.currentTrack){
        const el=queue.startTime?(Date.now()-queue.startTime)/1000:0;
        await safeEdit(queue.playerMsg,'',buildPlayerEmbed(queue.currentTrack,queue,el));
      }
      return interaction.reply({content:`🔀 Autoplay **${queue.autoplay?'ON':'OFF'}**.`,ephemeral:true});

    case 'queue': case 'q': {
      if (!queue.currentTrack&&!queue.tracks.length)
        return interaction.reply({content:'📋 Antrian kosong!',ephemeral:true});
      let desc=queue.currentTrack?`▶️ **Sekarang:** [${queue.currentTrack.title}](${queue.currentTrack.url})\n\n`:'';
      if (queue.tracks.length){
        desc+=queue.tracks.slice(0,10).map((t,i)=>`\`${i+1}.\` [${t.title}](${t.url}) — ${t.duration}`).join('\n');
        if (queue.tracks.length>10) desc+=`\n...dan ${queue.tracks.length-10} lagu lainnya.`;
      }
      return interaction.reply({embeds:[new EmbedBuilder().setColor(0x1db954)
        .setTitle(`📋 Antrian — ${queue.tracks.length} lagu`).setDescription(desc||'Kosong')]});
    }

    case 'clear':
      queue.tracks=[];
      return interaction.reply({content:'🗑️ Antrian dikosongkan!',ephemeral:true});

    case 'nowplaying': case 'np': {
      if (!queue.currentTrack) return interaction.reply({content:'❌ Tidak ada yang diputar.',ephemeral:true});
      const el=queue.startTime?(Date.now()-queue.startTime)/1000:0;
      return interaction.reply(buildPlayerEmbed(queue.currentTrack,queue,el));
    }

    case 'help': case 'h':
      return interaction.reply({embeds:[buildHelpEmbed()],ephemeral:false});

    case 'aliases':
      return interaction.reply({embeds:[buildAliasEmbed()],ephemeral:true});

    case 'changelog':
      return interaction.reply({embeds:[new EmbedBuilder().setColor(0x5865f2)
        .setTitle('📋 Changelog')
        .setDescription('**v2.0.0** — Slash commands + Autoplay + Player embed dengan tombol\n**v1.0.0** — Rilis awal dengan prefix commands')
      ],ephemeral:true});
  }
});

// ─── Prefix commands ──────────────────────────────────────────────────────────
client.on('messageCreate', async message=>{
  if (message.author.bot||!message.content.startsWith('!')||!message.guild) return;
  const args=message.content.slice(1).trim().split(/ +/);
  const cmd=args.shift().toLowerCase();
  const queue=getQueue(message.guild.id);

  try {
    if (cmd==='play'||cmd==='p') {
      const query=cleanQuery(args.join(' '));
      if (!query) return message.reply('❌ Kasih nama lagu atau link!');
      const vc=message.member?.voice?.channel;
      if (!vc) return message.reply('❌ Join voice channel dulu!');
      const loading=await message.reply(`🔍 Mencari **${query}**...`);
      queue.textChannel=message.channel;
      return handlePlay(loading, query, message.guild.id, vc, message.channel, message.author.username);
    }
    if (cmd==='search'||cmd==='sc') {
      const query=cleanQuery(args.join(' '));
      if (!query) return message.reply('❌ Kasih nama lagu yang mau dicari!');
      const loading=await message.reply(`🔍 Mencari **${query}**...`);
      let results;
      try { results=await searchMultiple(query, message.author.username); }
      catch(err){ return safeEdit(loading, `❌ ${err.message}`); }

      const desc=results.map((t,i)=>`\`${i+1}.\` [${t.title}](${t.url}) \`${t.duration}\``).join('\n');
      const embed=new EmbedBuilder()
        .setColor(0x5865f2)
        .setTitle(`🔍 Hasil pencarian: "${query}"`)
        .setDescription(desc)
        .setFooter({text:'Klik tombol untuk memutar lagu'});
      const row=new ActionRowBuilder().addComponents(
        results.map((t,i)=>
          new ButtonBuilder()
            .setCustomId(`search_pick_${t.url}`)
            .setLabel(`${i+1}. ${t.title.slice(0,40)}`)
            .setStyle(ButtonStyle.Secondary)
        )
      );
      return safeEdit(loading,'',{embeds:[embed], components:[row]});
    }
    if (cmd==='skip'||cmd==='s'){
      if (!queue.player||!queue.currentTrack) return message.reply('❌ Tidak ada yang diputar.');
      queue.loop=false;
      if (queue.ytdlpProc) { try{queue.ytdlpProc.kill('SIGKILL');}catch(_){} queue.ytdlpProc=null; }
      playNext(message.guild.id);
      return message.reply('⏭️ Di-skip!');
    }
    if (cmd==='stop') return cmdStopMsg(message,queue);
    if (cmd==='pause'){
      if (!queue.player) return message.reply('❌ Tidak ada yang diputar.');
      queue.player.pause();
      if (queue.playerMsg&&queue.currentTrack) safeEdit(queue.playerMsg,'',buildPausedEmbed(queue.currentTrack,queue));
      return message.reply('⏸️ Di-pause.');
    }
    if (cmd==='resume'||cmd==='r'){
      if (!queue.player) return message.reply('❌ Tidak ada yang diputar.');
      queue.player.unpause();
      if (queue.playerMsg&&queue.currentTrack) safeEdit(queue.playerMsg,'',buildPlayerEmbed(queue.currentTrack,queue,0));
      return message.reply('▶️ Dilanjutkan.');
    }
    if (cmd==='loop'||cmd==='l'){
      queue.loop=!queue.loop;
      return message.reply(`🔁 Loop **${queue.loop?'ON':'OFF'}**.`);
    }
    if (cmd==='autoplay'||cmd==='ap'){
      queue.autoplay=!queue.autoplay;
      return message.reply(`🔀 Autoplay **${queue.autoplay?'ON':'OFF'}**.`);
    }
    if (cmd==='queue'||cmd==='q') return cmdQueueMsg(message,queue);
    if (cmd==='clear'){ queue.tracks=[]; return message.reply('🗑️ Antrian dikosongkan!'); }
    if (cmd==='np'||cmd==='nowplaying'){
      if (!queue.currentTrack) return message.reply('❌ Tidak ada yang diputar.');
      const el=queue.startTime?(Date.now()-queue.startTime)/1000:0;
      return message.reply(buildPlayerEmbed(queue.currentTrack,queue,el));
    }
    if (cmd==='help'||cmd==='h') return message.reply({embeds:[buildHelpEmbed()]});
    if (cmd==='aliases') return message.reply({embeds:[buildAliasEmbed()]});
  } catch(err){
    console.error('cmd error:',err);
    message.reply(`❌ Error: ${err.message}`).catch(()=>{});
  }
});

// ─── Command helpers ──────────────────────────────────────────────────────────
async function cmdStopMsg(message, queue) {
  if (!queue.connection) return message.reply('❌ Bot tidak di voice channel.');
  queue.tracks=[];queue.currentTrack=null;queue.loop=false;
  if (queue.player){queue.player.removeAllListeners();queue.player.stop(true);}
  queue.connection?.destroy();
  if (queue.playerMsg){ await safeEdit(queue.playerMsg,'⏹️ Musik dihentikan.',{embeds:[],components:[]}); queue.playerMsg=null; }
  queue.connection=null;queue.player=null;
  queues.delete(message.guild.id);
  message.reply('⏹️ Bot keluar dari voice channel.');
}
async function cmdQueueMsg(message, queue) {
  if (!queue.currentTrack&&!queue.tracks.length) return message.reply('📋 Antrian kosong!');
  let desc=queue.currentTrack?`▶️ **Sekarang:** [${queue.currentTrack.title}](${queue.currentTrack.url})\n\n`:'';
  if (queue.tracks.length){
    desc+=queue.tracks.slice(0,10).map((t,i)=>`\`${i+1}.\` [${t.title}](${t.url}) — ${t.duration}`).join('\n');
    if (queue.tracks.length>10) desc+=`\n...dan ${queue.tracks.length-10} lagu lainnya.`;
  }
  message.reply({embeds:[new EmbedBuilder().setColor(0x1db954)
    .setTitle(`📋 Antrian — ${queue.tracks.length} lagu`).setDescription(desc||'Kosong')]});
}

function buildHelpEmbed() {
  return new EmbedBuilder().setColor(0x5865f2)
    .setTitle('🎵 Discord Music Bot — Semua Command')
    .setDescription('Pakai **Slash** (`/`) atau **prefix** (`!`)')
    .addFields(
      {name:'🎵 Playback',  value:'`/play` `/skip` `/stop` `/pause` `/resume`', inline:false},
      {name:'🔍 Search',    value:'`/search` `/sc` — Cari lagu & pilih dari hasil', inline:false},
      {name:'🎛️ Controls', value:'`/controls` `/c` `/ct` — Panel kontrol musik', inline:false},
      {name:'📋 Queue',     value:'`/queue` `/clear` `/nowplaying` `/np`', inline:false},
      {name:'🔁 Mode',      value:'`/loop` — Ulang lagu ini\n`/autoplay` — Putar lagu terkait otomatis', inline:false},
      {name:'ℹ️ Info',      value:'`/help` `/aliases` `/changelog`', inline:false},
      {name:'🖱️ Tombol',   value:'⏮ Replay  ⏸/▶️ Pause  ⏭ Skip  ✖ Stop  🔁 Loop', inline:false},
    ).setFooter({text:'Prefix: !play !p !search !sc !skip !s !stop !pause !resume !r !loop !l !autoplay !ap !queue !q !clear !np !help !h'});
}
function buildAliasEmbed() {
  return new EmbedBuilder().setColor(0x5865f2)
    .setTitle('🔤 Command Aliases')
    .addFields(
      {name:'/play',      value:'`/p` `!play` `!p`',              inline:true},
      {name:'/skip',      value:'`/s` `!skip` `!s`',              inline:true},
      {name:'/resume',    value:'`/r` `!resume` `!r`',            inline:true},
      {name:'/controls',  value:'`/control` `/c` `/ct`',          inline:true},
      {name:'/loop',      value:'`/l` `!loop` `!l`',              inline:true},
      {name:'/autoplay',  value:'`/ap` `!autoplay` `!ap`',        inline:true},
      {name:'/queue',     value:'`/q` `!queue` `!q`',             inline:true},
      {name:'/nowplaying',value:'`/np` `!np` `!nowplaying`',      inline:true},
      {name:'/help',      value:'`/h` `!help` `!h`',              inline:true},
    );
}

// ─── Login ────────────────────────────────────────────────────────────────────
const token=process.env.DISCORD_TOKEN;
if (!token){console.error('❌ DISCORD_TOKEN tidak ditemukan!');process.exit(1);}
client.login(token);